apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: gcr.io/global-approach-379820/binarycalculator
          name: mysql
          ports:
            - containerPort: 8080
              name: app